#!/bin/bash

TOTAL_SUITES=0 PASSED_SUITES=0 FAILED_SUITES=0
TOTAL_TESTS=0 PASSED_TESTS=0 FAILED_TESTS=0

strip_ansi() { sed -E 's/\x1B\[[0-9;]*[mK]//g'; }

TEST_FILES=$(find src/Tests -type f -name "*.test.js")

echo "🛠️ Running tests one by one..."
echo "----------------------------------------"

for TEST_FILE in $TEST_FILES; do
  echo "Running test: $TEST_FILE"

  TMP_FILE=$(mktemp)
  npx jest "$TEST_FILE" --ci >"$TMP_FILE" 2>&1

  OUT=$(strip_ansi <"$TMP_FILE")

  SUITES_LINE=$(echo "$OUT" | grep "Test Suites:") || SUITES_LINE=""
  TESTS_LINE=$(echo "$OUT" | grep "Tests:") || TESTS_LINE=""

  read -r CUR_SUITE_PASS CUR_SUITE_TOTAL <<<"$(echo "$SUITES_LINE" | grep -Eo '[0-9]+' | awk '{print $1,$NF}')"
  CUR_SUITE_PASS=${CUR_SUITE_PASS:-0}
  CUR_SUITE_TOTAL=${CUR_SUITE_TOTAL:-0}

  read -r CUR_TEST_PASS CUR_TEST_TOTAL <<<"$(echo "$TESTS_LINE" | grep -Eo '[0-9]+' | awk '{print $1,$NF}')"
  CUR_TEST_PASS=${CUR_TEST_PASS:-0}
  CUR_TEST_TOTAL=${CUR_TEST_TOTAL:-0}

  CUR_SUITE_FAIL=$((CUR_SUITE_TOTAL - CUR_SUITE_PASS))
  CUR_TEST_FAIL=$((CUR_TEST_TOTAL - CUR_TEST_PASS))

  TOTAL_SUITES=$((TOTAL_SUITES + CUR_SUITE_TOTAL))
  PASSED_SUITES=$((PASSED_SUITES + CUR_SUITE_PASS))
  FAILED_SUITES=$((FAILED_SUITES + CUR_SUITE_FAIL))

  TOTAL_TESTS=$((TOTAL_TESTS + CUR_TEST_TOTAL))
  PASSED_TESTS=$((PASSED_TESTS + CUR_TEST_PASS))
  FAILED_TESTS=$((FAILED_TESTS + CUR_TEST_FAIL))

  rm "$TMP_FILE"
  echo "Finished $TEST_FILE"
  echo "----------------------------------------"
done

if [ "$TOTAL_TESTS" -gt 0 ]; then
  PASS_RATE=$((100 * PASSED_TESTS / TOTAL_TESTS))
else
  PASS_RATE=0
fi

echo "🧩 Generating coverage report..."

mkdir -p coverage-summary

npx jest --coverage --coverageDirectory=coverage-summary --passWithNoTests \
  >coverage-summary/coverage-output.txt 2>&1

grep -A100 "All files" coverage-summary/coverage-output.txt \
  >coverage-summary/coverage-summary.txt

echo "🎯 Final Summary:"
echo "----------------------------------------"
echo "🧪 Test Suites:  total $TOTAL_SUITES, passed $PASSED_SUITES, failed $FAILED_SUITES"
echo "🧪 Tests:        total $TOTAL_TESTS,  passed $PASSED_TESTS,  failed $FAILED_TESTS"
echo "📈 Pass Rate:    $PASS_RATE%"
echo "----------------------------------------"
echo "🗂️  Coverage files generated in ./coverage-summary"
echo "   • lcov.info               (HTML report can be generated by running 'npx genhtml ...')"
echo "   • coverage-final.json     (raw data)"
echo "   • coverage-summary.txt    (text summary – open to view)"
echo "----------------------------------------"
